### PR TITLE
Fixes and updates

### PR DESCRIPTION
**Pull request by MisterDA**
The ppx path workaround doesn't work when lwd is vendored.

### CODE REVIEW

**Comment by MisterDA** [comment]
I've fixed the issues reported in ocaml-ci (from my fork). I consider this PR ready for merging.

**Review by let-def — COMMENTED** [review]
I am not sure removing that removing the fields is the way to go.
They were intended as a resource management primitive: to offer the possibility to observe which values were removed from a sequence.

This could be useful if a binding to a stateful library was implemented using Lwd (GTK/QT GUI, or some abstraction over GPU buffers, ...). It did not happen yet, but since the code is not trivial, I think it would be better to keep the fields and add the accessors that are missing.

**Review by let-def — CHANGES_REQUESTED** [review]
I am not sure removing that removing the fields is the way to go.
They were intended as a resource management primitive: to offer the possibility to observe which values were removed from a sequence.

This could be useful if a binding to a stateful library was implemented using Lwd (GTK/QT GUI, or some abstraction over GPU buffers, ...). It did not happen yet, but since the code is not trivial, I think it would be better to keep the fields and add the accessors that are missing.

Everything else looks good 👍

**Comment by MisterDA** [comment]
Thanks for the review, I've added accessors instead.

**Review by let-def — APPROVED** [review]

**Comment by let-def** [comment]
Thanks

**Comment by let-def** [comment]
Thanks for the PR. I integrated the changes manually and rebased.
Github doesn't show the PR as merged though it is. I guess we can close this?
Or maybe if you rebase manually your branch on master, it might pick up the update automatically.

This would be mostly for "historical" purpose: showing that the changes have been integrated.
Anyway thank you for the fixes, and sorry about my last messages: it was wrong to expose accessors, what needed to be done was to consider the xleaf/xjoin nodes when folding over dropped values.

**Comment by MisterDA** [comment]
> Thanks for the PR. I integrated the changes manually and rebased.

That's all good, thanks!

> Anyway thank you for the fixes, and sorry about my last messages: it was wrong to expose accessors, what needed to be done was to consider the xleaf/xjoin nodes when folding over dropped values.

Thank your for the fix!

**Pull request closed without merging**
